# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a803e9c532b821780131b122d3bdb8459ff74cb3866ced3aca5ad34f52321b12738c331a57875a02341efd39fbe1ba2590361afdfde17d41ac0675c7b56882

test:
  secret_key_base: 18d6b19a26e6bf1cca73c20fbbeb1e4f2c37f93aca1eba0b2b84ffc99070c86ab11dc5afafaadbd942eac5c1f51ea692253774a2ccb21c0a6421d2bf6dc30bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
